name: daelim_market
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  flutter_screenutil: 
  go_router: ^6.5.0
  image_picker: ^0.8.7+1
  firebase_core: 
  firebase_auth:
  cloud_firestore: 
  firebase_storage: 
  dropdown_button2: ^2.0.0
  flutter_secure_storage: 
  timer_builder: 
  intl: ^0.18.0
  connectivity: ^3.0.6
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  carousel_slider: ^4.2.1
  flutter_local_notifications: ^9.1.5
  permission_handler: ^10.2.0
  emoji_regex: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # Images
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/splash/

  fonts:
    - family: Jalnan
      fonts:
        - asset: assets/fonts/Jalnan.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#FFFFFF"
  android_12:
    # Light Mode
    image: assets/images/splash/ffffff.png
    branding: assets/images/splash/ffffff.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

    # Dark Mode
    image_dark: assets/images/splash/ffffff.png
    branding_dark: assets/images/splash/ffffff.png
    color_dark: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"